name: Publish Dataset

on:
  push:

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install DatasetTools
        run: |
          git clone --depth=1 https://github.com/CobaldAnnotation/DatasetTools.git
          cd DatasetTools
          pip install .
          cd ..

      - name: Build and publish
        env:
          HF_HUB_TOKEN: ${{ secrets.HF_HUB_TOKEN }}
        run: |
          python DatasetTools/build_and_publish.py enhanced.conllu CoBaLD/enhanced-cobald-dataset en